export interface Movie {
    id: number;
    title: string;
    year: number;
    genre: string[];
    rating: number;
    poster: string;
}

export const movies = [
    {
        id: 1,
        title: "Начало",
        year: 2010,
        genre: ["Фантастика", "Триллер", "Приключения"],
        rating: 8.8,
        poster: "https://avatars.mds.yandex.net/get-kinopoisk-image/1629390/8ab9a119-dd74-44f0-baec-0629797483d7/600x900",
        description:
            "Доминик Кобб — профессиональный вор, который крадет секреты из подсознания через сны. Ему предлагают сделать невозможное — внедрить идею в чужой разум.",
        director: "Кристофер Нолан",
        cast: ["Леонардо Ди Каприо", "Джозеф Гордон-Левитт", "Эллен Пейдж"],
        duration: 148,
        language: "Английский",
        country: "США",
        trailer: "https://www.youtube.com/watch?v=YoHD9XEInc0",
    },
    {
        id: 2,
        title: "Интерстеллар",
        year: 2014,
        genre: ["Фантастика", "Драма", "Приключения"],
        rating: 8.6,
        poster: "https://image.tmdb.org/t/p/w500/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg",
        description:
            "Группа исследователей отправляется через космическую червоточину в поисках нового дома для человечества.",
        director: "Кристофер Нолан",
        cast: ["Мэттью МакКонахи", "Энн Хэтэуэй", "Джессика Честейн"],
        duration: 169,
        language: "Английский",
        country: "США",
        trailer: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
    },
    {
        id: 3,
        title: "Матрица",
        year: 1999,
        genre: ["Фантастика", "Боевик"],
        rating: 8.7,
        poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
        description:
            "Нео обнаруживает, что мир, в котором он живет, — всего лишь иллюзия, созданная машинами для порабощения человечества.",
        director: "Лана и Лилли Вачовски",
        cast: ["Киану Ривз", "Лоренс Фишберн", "Кэрри-Энн Мосс"],
        duration: 136,
        language: "Английский",
        country: "США",
        trailer: "https://www.youtube.com/watch?v=vKQi3bBA1y8",
    },
    {
        id: 4,
        title: "Властелин колец: Братство Кольца",
        year: 2001,
        genre: ["Фэнтези", "Приключения"],
        rating: 8.8,
        poster: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
        description:
            "Фродо Бэггинс отправляется в опасное путешествие, чтобы уничтожить Кольцо Всевластья и спасти Средиземье.",
        director: "Питер Джексон",
        cast: ["Элайджа Вуд", "Иэн Маккеллен", "Вигго Мортенсен"],
        duration: 178,
        language: "Английский",
        country: "Новая Зеландия",
        trailer: "https://www.youtube.com/watch?v=V75dMMIW2B4",
    },
    {
        id: 5,
        title: "Темный рыцарь",
        year: 2008,
        genre: ["Боевик", "Криминал", "Драма"],
        rating: 9.0,
        poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        description:
            "Бэтмен сражается с хаосом, который сеет Джокер, угрожая уничтожить Готэм.",
        director: "Кристофер Нолан",
        cast: ["Кристиан Бэйл", "Хит Леджер", "Майкл Кейн"],
        duration: 152,
        language: "Английский",
        country: "США",
        trailer: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
    },
    {
        id: 6,
        title: "Форрест Гамп",
        year: 1994,
        genre: ["Драма", "Комедия"],
        rating: 8.8,
        poster: "https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
        description:
            "Жизнь Форреста Гампа — простого и доброго человека, который случайно становится участником значимых событий XX века.",
        director: "Роберт Земекис",
        cast: ["Том Хэнкс", "Робин Райт", "Гэри Синиз"],
        duration: 142,
        language: "Английский",
        country: "США",
        trailer: "https://www.youtube.com/watch?v=bLvqoHBptjg",
    },
    {
        id: 7,
        title: "Бегущий по лезвию 2049",
        year: 2017,
        genre: ["Фантастика", "Триллер"],
        rating: 8.0,
        poster: "https://image.tmdb.org/t/p/w500/aMpyrCizvSdc0UIMblJ1srVgAEF.jpg",
        description:
            "Новый бегущий по лезвию, офицер Кей, раскрывает давно скрытую тайну, которая может погрузить остатки общества в хаос.",
        director: "Дени Вильнёв",
        cast: ["Райан Гослинг", "Харрисон Форд", "Ана де Армас"],
        duration: 164,
        language: "Английский",
        country: "США",
        trailer: "https://www.youtube.com/watch?v=gCcx85zbxz4",
    },
    {
        id: 8,
        title: "Джокер",
        year: 2019,
        genre: ["Драма", "Криминал", "Триллер"],
        rating: 8.4,
        poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
        description:
            "История происхождения одного из самых известных злодеев комиксов — Джокера.",
        director: "Тодд Филлипс",
        cast: ["Хоакин Феникс", "Роберт Де Ниро", "Зази Битц"],
        duration: 122,
        language: "Английский",
        country: "США",
        trailer: "https://www.youtube.com/watch?v=zAGVQLHvwOY",
    },
    {
        id: 9,
        title: "Побег из Шоушенка",
        year: 1994,
        genre: ["Драма", "Криминал"],
        rating: 9.3,
        poster: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
        description:
            "История дружбы и надежды двух заключённых, которые пытаются обрести свободу в тюрьме Шоушенк.",
        director: "Фрэнк Дарабонт",
        cast: ["Тим Роббинс", "Морган Фриман", "Боб Гантон"],
        duration: 142,
        language: "Английский",
        country: "США",
        trailer: "https://www.youtube.com/watch?v=6hB3S9bIaco",
    },
    {
        id: 10,
        title: "Гладиатор",
        year: 2000,
        genre: ["Приключения", "Драма", "Исторический"],
        rating: 8.5,
        poster: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
        description:
            "Римский генерал становится гладиатором и ищет справедливость за предательство и смерть семьи.",
        director: "Ридли Скотт",
        cast: ["Рассел Кроу", "Хоакин Феникс", "Конни Нильсен"],
        duration: 155,
        language: "Английский",
        country: "США",
        trailer: "https://www.youtube.com/watch?v=owK1qxDselE",
    },
    {
        id: 11,
        title: "Титаник",
        year: 1997,
        genre: ["Драма", "Мелодрама"],
        rating: 7.8,
        poster: "https://upload.wikimedia.org/wikipedia/ru/1/19/Titanic_%28Official_Film_Poster%29.png",
        description:
            "История любви между Джеком и Розой на фоне трагедии затонувшего лайнера 'Титаник'.",
        director: "Джеймс Кэмерон",
        cast: ["Леонардо Ди Каприо", "Кейт Уинслет", "Билли Зейн"],
        duration: 195,
        language: "Английский",
        country: "США",
        trailer: "https://www.youtube.com/watch?v=zCy5WQ9S4c0",
    },
    {
        id: 12,
        title: "Гарри Поттер и философский камень",
        year: 2001,
        genre: ["Фэнтези", "Приключения", "Семейный"],
        rating: 7.6,
        poster: "https://upload.wikimedia.org/wikipedia/ru/b/b4/Harry_Potter_and_the_Philosopher%27s_Stone_%E2%80%94_movie.jpg",
        description:
            "Юный волшебник Гарри Поттер поступает в школу Хогвартс и начинает изучать магию.",
        director: "Крис Коламбус",
        cast: ["Дэниэл Рэдклифф", "Эмма Уотсон", "Руперт Гринт"],
        duration: 152,
        language: "Английский",
        country: "Великобритания",
        trailer: "https://www.youtube.com/watch?v=VyHV0BRtdxo",
    },
    {
        id: 13,
        title: "Паразиты",
        year: 2019,
        genre: ["Драма", "Триллер", "Комедия"],
        rating: 8.6,
        poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
        description:
            "Семья бедных людей хитростью внедряется в жизнь богатой семьи, что приводит к неожиданным последствиям.",
        director: "Пон Чжун Хо",
        cast: ["Сон Кан Хо", "Чо Ё Джон", "Чан Хён Чжу"],
        duration: 132,
        language: "Корейский",
        country: "Южная Корея",
        trailer: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
    },
    {
        id: 14,
        title: "Звёздные войны: Эпизод IV — Новая надежда",
        year: 1977,
        genre: ["Фантастика", "Приключения"],
        rating: 8.6,
        poster: "https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
        description:
            "Молодой Люк Скайуокер вступает в борьбу с Империей, чтобы спасти галактику.",
        director: "Джордж Лукас",
        cast: ["Марк Хэмилл", "Харрисон Форд", "Кэрри Фишер"],
        duration: 121,
        language: "Английский",
        country: "США",
        trailer: "https://www.youtube.com/watch?v=vZ734NWnAHA",
    },
    {
        id: 15,
        title: "В поисках Немо",
        year: 2003,
        genre: ["Анимация", "Приключения", "Комедия"],
        rating: 8.1,
        poster: "https://upload.wikimedia.org/wikipedia/ru/2/29/Finding_Nemo.jpg",
        description:
            "Отец-рыба Марлин путешествует по океану в поисках своего потерянного сына Немо.",
        director: "Эндрю Стэнтон",
        cast: ["Альберт Брукс", "Эллен Дедженерес", "Александр Гулд"],
        duration: 100,
        language: "Английский",
        country: "США",
        trailer: "https://www.youtube.com/watch?v=wZdpNglLbt8",
    },
];
